[Service]
ExecStart=
ExecStart=/usr/bin/prometheus-node-exporter --web.listen-address=192.168.1.5:9100

# The exporter is read-only and accepts connections only from Prometheus.
IPAddressAllow=192.168.1.24/32
IPAddressDeny=any
NoNewPrivileges=yes
CapabilityBoundingSet=
AmbientCapabilities=
PrivateTmp=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectSystem=strict
RestrictAddressFamilies=AF_INET AF_INET6 AF_NETLINK
RestrictRealtime=yes
RestrictSUIDSGID=yes
LockPersonality=yes
MemoryDenyWriteExecute=yes
SystemCallArchitectures=native
