SET LOCAL lock_timeout = '2s';
SET LOCAL statement_timeout = '30s';

ALTER TABLE public.soc_cases
    ADD COLUMN risk_score smallint,
    ADD COLUMN risk_level text,
    ADD COLUMN ai_confidence smallint,
    ADD COLUMN ai_verdict text,
    ADD COLUMN analyst_verdict text,
    ADD COLUMN analyst_reason text,
    ADD COLUMN analyst_notes text,
    ADD COLUMN initial_priority text,
    ADD COLUMN final_priority text,
    ADD COLUMN priority_reason text,
    ADD COLUMN assigned_at timestamp with time zone,
    ADD COLUMN acknowledged_at timestamp with time zone,
    ADD COLUMN investigation_started_at timestamp with time zone,
    ADD COLUMN resolved_at timestamp with time zone,
    ADD COLUMN closed_at timestamp with time zone,
    ADD COLUMN ack_sla_deadline timestamp with time zone,
    ADD COLUMN investigation_sla_deadline timestamp with time zone,
    ADD COLUMN sla_status text,
    ADD COLUMN assessment_version text,
    ADD COLUMN scoring_version text;

ALTER TABLE public.soc_cases
    ADD CONSTRAINT soc_cases_risk_score_check CHECK (risk_score BETWEEN 0 AND 100) NOT VALID,
    ADD CONSTRAINT soc_cases_risk_level_check CHECK (risk_level IN ('LOW','MEDIUM','HIGH','VERY_HIGH','CRITICAL')) NOT VALID,
    ADD CONSTRAINT soc_cases_ai_confidence_check CHECK (ai_confidence BETWEEN 0 AND 100) NOT VALID,
    ADD CONSTRAINT soc_cases_ai_verdict_check CHECK (ai_verdict IN ('FALSE_POSITIVE','BENIGN_POSITIVE','SUSPICIOUS','TRUE_POSITIVE','INCONCLUSIVE')) NOT VALID,
    ADD CONSTRAINT soc_cases_analyst_verdict_check CHECK (analyst_verdict IN ('PENDING','FALSE_POSITIVE','BENIGN_POSITIVE','SUSPICIOUS','TRUE_POSITIVE','INCONCLUSIVE')) NOT VALID,
    ADD CONSTRAINT soc_cases_initial_priority_check CHECK (initial_priority IN ('p1','p2','p3','p4')) NOT VALID,
    ADD CONSTRAINT soc_cases_final_priority_check CHECK (final_priority IN ('p1','p2','p3','p4')) NOT VALID,
    ADD CONSTRAINT soc_cases_sla_status_check CHECK (sla_status IN ('ON_TIME','WARNING','BREACHED')) NOT VALID;

CREATE TABLE public.soc_assessments (
    assessment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL REFERENCES public.soc_cases(id),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
    model_alias text NOT NULL,
    analysis_level text NOT NULL CHECK (analysis_level IN ('L1','L2')),
    ai_verdict text NOT NULL CHECK (ai_verdict IN ('FALSE_POSITIVE','BENIGN_POSITIVE','SUSPICIOUS','TRUE_POSITIVE','INCONCLUSIVE')),
    confidence_score smallint NOT NULL CHECK (confidence_score BETWEEN 0 AND 100),
    risk_score smallint NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    risk_level text NOT NULL CHECK (risk_level IN ('LOW','MEDIUM','HIGH','VERY_HIGH','CRITICAL')),
    summary text NOT NULL,
    hypothesis text NOT NULL,
    risk_factors jsonb NOT NULL DEFAULT '[]'::jsonb,
    positive_points smallint NOT NULL CHECK (positive_points >= 0),
    negative_points smallint NOT NULL CHECK (negative_points >= 0),
    supporting_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    contradicting_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    missing_information jsonb NOT NULL DEFAULT '[]'::jsonb,
    mitre_correlation jsonb NOT NULL DEFAULT '[]'::jsonb,
    recommendations jsonb NOT NULL DEFAULT '[]'::jsonb,
    assessment_version text NOT NULL,
    scoring_version text NOT NULL,
    confidence_version text NOT NULL,
    evidence_package_version text NOT NULL,
    evidence_snapshot jsonb NOT NULL,
    supersedes_assessment_id bigint REFERENCES public.soc_assessments(assessment_id)
);

CREATE INDEX soc_assessments_case_created_idx
    ON public.soc_assessments (case_id, created_at DESC);

CREATE TABLE public.soc_feedback (
    feedback_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id bigint NOT NULL REFERENCES public.soc_cases(id),
    assessment_id bigint REFERENCES public.soc_assessments(assessment_id),
    previous_analyst_verdict text CHECK (previous_analyst_verdict IS NULL OR previous_analyst_verdict IN ('PENDING','FALSE_POSITIVE','BENIGN_POSITIVE','SUSPICIOUS','TRUE_POSITIVE','INCONCLUSIVE')),
    analyst_verdict text NOT NULL CHECK (analyst_verdict IN ('FALSE_POSITIVE','BENIGN_POSITIVE','SUSPICIOUS','TRUE_POSITIVE','INCONCLUSIVE')),
    reason text NOT NULL,
    notes text NOT NULL,
    analyst text NOT NULL,
    request_id text NOT NULL,
    ai_verdict_snapshot text CHECK (ai_verdict_snapshot IN ('FALSE_POSITIVE','BENIGN_POSITIVE','SUSPICIOUS','TRUE_POSITIVE','INCONCLUSIVE')),
    ai_confidence_snapshot smallint CHECK (ai_confidence_snapshot BETWEEN 0 AND 100),
    risk_score_snapshot smallint CHECK (risk_score_snapshot BETWEEN 0 AND 100),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX soc_feedback_case_created_idx
    ON public.soc_feedback (case_id, created_at DESC);
